server:
  port: 8081
  servlet:
    context-path: /member
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_member?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 19831068773Ljs
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
  application:
    name: member
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.eddie.train.member.mapper: TRACE
