server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: member
          predicates:
          - Path=/member/**
          uri: http://127.0.0.1:8081
  jackson:
    time-zone: Asia/Shanghai