server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: member
          predicates:
            - Path=/member/**
#          uri: http://127.0.0.1:8081
          uri: lb://member
        - id: business
          predicates:
            - Path=/business/**
          uri: lb://business
        - id: batch
          predicates:
            - Path=/batch/**
          uri: lb://batch
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许请求来源（老版本叫allowedOrigin）
            allowedOriginPatterns: "*"
            # 允许携带的头信息
            allowedHeaders: "*"
            # 允许的请求方式
            allowedMethods: "*"
            # 是否允许携带cookie
            allowCredentials: true
            # 跨域检测的有效期
            maxAge: 3600
  jackson:
    time-zone: Asia/Shanghai
  application:
    name: gateway