###
GET http://localhost:8080/batch/hello
Accept: application/json

###
POST http://localhost:8080/batch/admin/job/run
Content-Type: application/json

{
  "name": "com.eddie.train.batch.job.DailyTrainJob",
  "jobGroupName": "default"
}

###
POST http://localhost:8080/batch/admin/job/delete
Content-Type: application/json

{
  "name": "com.eddie.train.batch.job.DailyTrainJob",
  "jobGroupName": "default"
}



