//gtr gtrp 快捷生成
GET http://localhost:8080/member/member/count
Accept: application/json
###
POST http://localhost:8080/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=123456789
###
POST http://localhost:8080/member/member/sendCode
Content-Type: application/x-www-form-urlencoded

mobile=19831068773
###
POST http://localhost:8080/member/member/login
Content-Type: application/json

{
  "mobile": "19831068773",
  "code": "8888"
}

###

