server:
  port: 8083
  servlet:
    context-path: /batch
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_batch?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 19831068773Ljs
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.eddie.train.batch.mapper: TRACE
